### PR TITLE
Channel message issue 26

### PR DESCRIPTION
**Pull request by Isioblast**
Everything should be done, every test pass with the command "npx jest --runInBand". Except for the channel test that are in another issue

### CODE REVIEW

**Review by kbarbry — CHANGES_REQUESTED** [review]
If content is empty, it will be checked by the controller, no need for tests, exceptions and detection in services for that, besides that everything is good!

**Review by Chicanoss — APPROVED** [review]
Good work, seems good, i'll use some of your code to set-up private message !

**Review by kbarbry — CHANGES_REQUESTED** [review]
Change the updatedAt field in db by adding a @updatedat decorator

**Comment by Isioblast** [comment]
> updatedat

The decorator @updateAt does not exist 🍰

**Review by kbarbry — CHANGES_REQUESTED** [review]
Same exception error

**Pull request merged**
